# Generated by Django 5.2.15 on 2026-06-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='compras.buyer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='compras.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
