# Generated by Django 5.2.15 on 2026-06-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('beneficiary_name', models.CharField(max_length=180)),
                ('goal_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='raffles/')),
                ('price_per_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_numbers', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('draw_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('finished', 'Finalizada'), ('canceled', 'Cancelada')], default='draft', max_length=20)),
                ('winner_number', models.PositiveIntegerField(blank=True, null=True)),
                ('winner_name', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaffleNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponivel'), ('reserved', 'Reservado'), ('paid', 'Pago'), ('canceled', 'Cancelado')], default='available', max_length=20)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='rifa.raffle')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('raffle', 'number'), name='unique_raffle_number')],
            },
        ),
    ]
