# Generated by Django 5.2.15 on 2026-06-04 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reserved', 'Reservada'), ('paid', 'Paga'), ('expired', 'Expirada'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('reservation_expires_at', models.DateTimeField()),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='compras.buyer')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rifa.raffle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_numbers', to='compras.purchase')),
                ('raffle_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rifa.rafflenumber')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='numbers',
            field=models.ManyToManyField(related_name='purchases', through='compras.PurchaseNumber', to='rifa.rafflenumber'),
        ),
        migrations.AddConstraint(
            model_name='purchasenumber',
            constraint=models.UniqueConstraint(fields=('purchase', 'raffle_number'), name='unique_purchase_raffle_number'),
        ),
    ]
