# Generated by Django 5.2.15 on 2026-06-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_buyer_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserva criada"),
                            ("payment_checked", "Pagamento consultado"),
                            ("payment_confirmed", "Pagamento confirmado"),
                            ("expired", "Reserva expirada"),
                            ("released", "Reserva liberada"),
                            ("sync_failed", "Falha de sincronizacao"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source", models.CharField(default="system", max_length=40)),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("buyer_name", models.CharField(max_length=241)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_phone", models.CharField(max_length=30)),
                ("buyer_cpf", models.CharField(max_length=14)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_events",
                        to="compras.buyer",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="compras.purchase",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
