# Generated by Django 5.2.15 on 2026-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_purchaseevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseevent",
            name="numbers_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
